export const CATEGORIES = [
  { id: 1, name: 'concerts', name_ru: 'Концерты' },
  { id: 2, name: 'theater', name_ru: 'Театр' },
  { id: 3, name: 'sports', name_ru: 'Спорт' },
  { id: 4, name: 'exhibitions', name_ru: 'Выставки' },
  { id: 5, name: 'cinema', name_ru: 'Кино' },
  { id: 6, name: 'exhibitions', name_ru: 'Выставки' },
  { id: 7, name: 'museums', name_ru: 'Музеи' },
  { id: 8, name: 'quest', name_ru: 'Квест комната' },
  { id: 9, name: 'extreme', name_ru: 'Экстрим' },
  { id: 10, name: 'daily', name_ru: 'Daily' },
  { id: 11, name: 'rage_room', name_ru: 'Комната гнева' },
  { id: 12, name: 'billiards', name_ru: 'Бильярд' },
  { id: 13, name: 'bowling', name_ru: 'Боулинг' },
];

export const CITIES = [
  { id: 1, name: 'Москва' },
  { id: 2, name: 'Санкт-Петербург' },
  { id: 4, name: 'Сочи' },
  { id: 5, name: 'Новосибирск' },
  { id: 6, name: 'Альметьевск' },
  { id: 7, name: 'Ангарск' },
  { id: 8, name: 'Армавир' },
  { id: 9, name: 'Архангельск' },
  { id: 10, name: 'Астрахань' },
  { id: 11, name: 'Балаково' },
  { id: 12, name: 'Балашиха' },
  { id: 13, name: 'Барнаул' },
  { id: 14, name: 'Батайск' },
  { id: 15, name: 'Белгород' },
  { id: 16, name: 'Березники' },
  { id: 17, name: 'Бийск' },
  { id: 18, name: 'Братск' },
  { id: 19, name: 'Брянск' },
  { id: 20, name: 'Буйнакск' },
  { id: 21, name: 'Великий Новгород' },
  { id: 22, name: 'Владивосток' },
  { id: 23, name: 'Владикавказ' },
  { id: 24, name: 'Волгоград' },
  { id: 25, name: 'Воронеж' },
  { id: 26, name: 'Дербент' },
  { id: 27, name: 'Екатеринбург' },
  { id: 28, name: 'Краснодар' },
  { id: 29, name: 'Красноярск' },
  { id: 30, name: 'Ростов-на-Дону' },
  { id: 31, name: 'Грозный' },
  { id: 32, name: 'Хасавюрт' },
  { id: 33, name: 'Казань' },
];

export const EVENT_TEMPLATES = [
  { id: 1, name: 'Сальвадор Дали & Пабло Пикассо', description: 'Откройте мир двух гениев искусства и вдохновитесь их шедеврами. Уникальная экспозиция для всех любителей живописи.', category_id: 6, ticket_image_url: 'https://artchive.ru/res/media/img/oy800/exposition/c22/678496@2x.jpg', is_active: true },
  { id: 2, name: 'VR Gallery', description: 'Полное погружение в виртуальные галереи с интерактивными экспонатами. Перенеситесь внутрь картин и создайте свои впечатления.', category_id: 6, ticket_image_url: 'https://www.marinabaysands.com/content/dam/revamp/ASMrevamp/VRgallery/VR-Gallery-Photo-Shoot-1-800x490.jpg', is_active: true },
  { id: 3, name: 'Реальный космос', description: 'Путешествие по Вселенной в интерактивной выставке. Узнайте о планетах, звёздах и космосе своими глазами.', category_id: 6, ticket_image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbou2jpU3dM2uViVkFfBxFw_vmZsD54TMMdQ&s', is_active: true },
  { id: 4, name: 'Энди Уорхол и русское искусство', description: 'Поп-арт встречает классику: яркие работы и современные интерпретации. Идеально для любителей искусства и фотографий.', category_id: 6, ticket_image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRCG3ocLudpB89cv9srmMsuizRDpASa5HJvw&s', is_active: true },
  { id: 5, name: 'Айвазовский. Кандинский. Живые полотна', description: 'Ожившие шедевры на мультимедийных экранах. Впечатляющее шоу для всей семьи.', category_id: 6, ticket_image_url: 'https://s3.afisha.ru/mediastorage/22/5e/a84badf567224497bf0dac225e22.jpg', is_active: true },
  { id: 6, name: 'Музей восковых фигур', description: 'Реалистичные фигуры знаменитостей и исторических личностей. Сделайте фото с кумирами.', category_id: 7, ticket_image_url: 'https://kuda-kazan.ru/uploads/5acced441044b6f1ca31fe364a3003dd.jpg', is_active: true },
  { id: 7, name: 'VR Музей', description: 'Интерактивные выставки в виртуальной реальности. Исследуйте экспозиции, как будто внутри них.', category_id: 7, ticket_image_url: 'https://vinchi-interactive.ru/wp-content/uploads/2023/08/vr-111-min.jpg', is_active: true },
  { id: 8, name: 'Музей истории оружия', description: 'Коллекция оружия от древности до современности. Узнайте историю через уникальные экспонаты.', category_id: 7, ticket_image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Weapon_history_museum_39.jpg/1200px-Weapon_history_museum_39.jpg', is_active: true },
  { id: 9, name: 'Музей драгоценностей', description: 'Редкие украшения и драгоценные камни. Погрузитесь в мир роскоши и красоты.', category_id: 7, ticket_image_url: 'https://it.latuaitalia.ru/wp-content/uploads/2016/04/comune.vicenza.it_2.jpg', is_active: true },
  { id: 10, name: 'Планетарий Saturn', description: 'Захватывающие космические шоу под куполом планетария. Путешествие среди звёзд для всей семьи.', category_id: 7, ticket_image_url: 'https://supernova.eso.org/static/archives/images/screen/upr_IMG_6320-cc.jpg', is_active: true },
  { id: 11, name: 'Последняя экскурсия. Выжить любой ценой', description: 'Хоррор-квест с актёрами. Вы оказались в заброшенном музее с темной историей. Успейте выбраться за 60 минут.', category_id: 8, ticket_image_url: 'https://www.kvestinfo.ru/upload/iblock/30b/30b170bfe799ac5a951a534d0a58cce3_500x335.jpg', is_active: true },
  { id: 12, name: 'Обитель проклятых', description: 'Мистический квест в атмосфере старинного особняка. Разгадайте тайну проклятия семьи.', category_id: 8, ticket_image_url: 'https://nsk.mir-kvestov.ru/uploads/quest_photos/34566/kvest-obitel-proklyatyh-quest-stars-323337fe_large.jpg?v=1761571873', is_active: true },
  { id: 13, name: 'Побег из Алькатраса', description: 'Классический побег из тюрьмы. Логические загадки и механические головоломки.', category_id: 8, ticket_image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvdDgoVd6R71aL-58y3jST7r2uYtBwxVwflA&s', is_active: true },
  { id: 14, name: 'Ограбление банка', description: 'Командный квест. Спланируйте и проведите идеальное ограбление.', category_id: 8, ticket_image_url: 'https://qimnata.com/dist/pict_rooms/NAX8ueFt.jpg', is_active: true },
  { id: 15, name: 'Машина Времени', description: 'Научно-фантастический квест с путешествием по разным эпохам.', category_id: 8, ticket_image_url: 'https://staryj-oskol.mir-kvestov.ru/uploads/quest_photos/7652/kvest-mashina-vremeni-kvest-mashina-8b206cd5_large.jpg?v=1762855471', is_active: true },
  { id: 16, name: 'Не дыши', description: 'Стелс-хоррор квест. Пробирайтесь через дом слепого убийцы.', category_id: 8, ticket_image_url: 'https://questhunter.info/wp-content/uploads/sites/9/2023/10/79.jpg', is_active: true },
  { id: 17, name: 'Аутласт', description: 'Экстремальный хоррор-квест по мотивам игры. Только для смелых.', category_id: 8, ticket_image_url: 'https://mir-kvestov.ru/uploads/quest_photos/26054/kvest-outlast-quest-stars-3e78602f.jpg?v=1761644183', is_active: true },
  { id: 18, name: 'Шерлок', description: 'Детективный квест. Расследуйте преступление вместе с великим сыщиком.', category_id: 8, ticket_image_url: 'https://topkvest.by/storage/thumb/quest_image/w800_h600_01K33PHCKAXSDG2C727MJBY1NW.jpeg', is_active: true },
  { id: 19, name: 'Аэротруба', description: 'Полёт в аэродинамической трубе. Ощущение свободного падения без прыжка с самолёта.', category_id: 9, ticket_image_url: 'https://ulet.pro/sites/default/files/field/image/blog_post/aerotruba-bezopasnyy-sposob.jpg', is_active: true },
  { id: 20, name: 'Прогулка на лошадях', description: 'Конная прогулка по живописным маршрутам с инструктором.', category_id: 9, ticket_image_url: 'https://resize.tripster.ru/CwGIW9nfE-TxrqgFc9pbT_yWhas=/fit-in/1220x600/filters:no_upscale()/https://cdn.tripster.ru/photos/d77e8130-139a-4c81-9faa-444d14603983.jpg', is_active: true },
  { id: 21, name: 'Картинг', description: 'Гонки на профессиональных картах. Соревнуйтесь с друзьями на скорость.', category_id: 9, ticket_image_url: 'https://avatars.mds.yandex.net/get-altay/14112077/2a00000191e1042ff59bc038768f19a644a3/L_height', is_active: true },
  { id: 22, name: 'Пейнтбол', description: 'Командная игра в пейнтбол на оборудованной площадке.', category_id: 9, ticket_image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_VzElIKBhcpDFrp1foiRI475b-PZrLRqXAg&s', is_active: true },
  { id: 23, name: 'Прогулка на квадроциклах', description: 'Экстремальная поездка по бездорожью на мощных квадроциклах.', category_id: 9, ticket_image_url: 'https://cdn-ua.bodo.gift/resize/upload/files/cm-experience/103/102695/images_file/all_all_big-t1585036987-r1w768h425q90zc1.jpg', is_active: true },
  { id: 24, name: 'Профессиональный Тир', description: 'Стрельба из различных видов оружия под руководством инструктора.', category_id: 9, ticket_image_url: 'https://cdn-ua.bodo.gift/resize/upload/files/cm-experience/106/105781/images_file/all_all_big-t1701090100-r1w568h318q90zc1.jpg', is_active: true },
  { id: 25, name: 'Дегустация сыров и вин', description: 'Изысканная дегустация элитных сыров и вин с сомелье. 6 сортов вина и 8 видов сыра.', category_id: 10, ticket_image_url: 'https://s0.rbk.ru/v6_top_pics/media/img/2/37/347243227110372.webp', is_active: true },
  { id: 26, name: 'Дегустация Пива', description: 'Крафтовые сорта пива от локальных пивоварен с закусками.', category_id: 10, ticket_image_url: 'https://2l-pub.ru/upload/medialibrary/72a/vt51vdajv2yqu8ewl936b3e32i8ou3ph.jpeg', is_active: true },
  { id: 27, name: 'Дегустация Чая', description: 'Чайная церемония с редкими сортами чая из Китая, Японии и Индии.', category_id: 10, ticket_image_url: 'https://welcome.mosreg.ru/storage/images/event/2023/04/img_642e9feb3b4ba.jpg', is_active: true },
  { id: 28, name: 'Кинотеатр на Крыше', description: 'Показ фильмов под открытым небом с потрясающим видом на город.', category_id: 10, ticket_image_url: 'https://lh6.googleusercontent.com/proxy/buGsdzad1b1jwTVf-lwwU1UR7E0_PJ1eROwVYcmt0lS9TZV1JXC2QXp-ztZvkzTl2BM9vdBObWiov4CPAf7zivUYyvGCrT1l', is_active: true },
  { id: 29, name: 'Контактный зоопарк', description: 'Общение с ручными животными: кролики, козы, ламы, еноты и другие.', category_id: 10, ticket_image_url: 'https://avatars.mds.yandex.net/get-altay/11302718/2a000001901a6a33284430327503fe56714b/L_height', is_active: true },
  { id: 30, name: 'Party Bus', description: 'Вечеринка в движении! Автобус с музыкой, светом и танцполом.', category_id: 10, ticket_image_url: 'https://www.limuzynki.pl/wpcu/2023/06/wnetrze-party-bus-3.jpg', is_active: true },
  { id: 31, name: 'Выставка "Retro life"', description: 'Погружение в атмосферу 60-80х годов. Ретро-техника, мода и интерьеры.', category_id: 10, ticket_image_url: null, is_active: false },
  { id: 32, name: 'Фестиваль японской культуры', description: 'Косплей, аниме, манга, японская кухня и мастер-классы.', category_id: 10, ticket_image_url: 'https://www.ru.emb-japan.go.jp/japan2018/common/images/article/mo7193-3.jpg', is_active: true },
  { id: 33, name: 'Кулинарный мастер класс', description: 'Готовим изысканные блюда вместе с профессиональным шефом.', category_id: 10, ticket_image_url: 'https://tomsk.ultrapodarki.ru/upload/iblock/fce/fce734cf7f9f5588ba297d6595a87028.jpg', is_active: true },
  { id: 34, name: 'Фестиваль иллюзионистов', description: 'Шоу-программа от лучших фокусников и иллюзионистов страны.', category_id: 10, ticket_image_url: 'https://www.afisha.uz/uploads/media/2024/04/d401374706701708c82b728d4964dcfa_l.jpg', is_active: true },
  { id: 35, name: 'Гастро-тур "Tasty"', description: 'Гастрономическое путешествие по лучшим заведениям города.', category_id: 10, ticket_image_url: null, is_active: false },
  { id: 36, name: 'Мотошоу "Extreme"', description: 'Каскадёрские трюки на мотоциклах. Огонь, скорость, адреналин!', category_id: 10, ticket_image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTPDX4LzFElEKGMHX567kVuLeeUEnt74ocsw&s', is_active: true },
  { id: 37, name: 'Лазерное шоу с диджеем', description: 'Ночное лазерное шоу с лучшими диджеями города.', category_id: 10, ticket_image_url: 'https://i.ytimg.com/vi/G3WxM4mhEFA/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGBogLSh_MA8=&rs=AOn4CLBdS0Mhc_0gOtzesYrVnWSO7BF9Vg', is_active: true },
  { id: 38, name: 'Романтика на закате', description: 'Романтический вечер на крыше с видом на закат. Шампанское и фуршет.', category_id: 10, ticket_image_url: 'https://i.pinimg.com/736x/62/ca/60/62ca60ed68725859f3a27d4c7193a71e.jpg', is_active: true },
  { id: 39, name: 'Фестиваль BBQ & Smoke', description: 'Фестиваль барбекю: мясо на гриле, копчёности и street food.', category_id: 10, ticket_image_url: 'https://img.restoclub.ru/uploads/article/9/8/d/7/98d703b781f23fc2db166497664d8b42_w828_h552--big.jpg', is_active: true },
  { id: 40, name: 'Комната гнева', description: 'Снимите стресс! Разбейте всё, что угодно: посуду, технику, мебель. Безопасно и весело.', category_id: 11, ticket_image_url: 'https://images.aif.by/007/836/a70cc50074418a1821b4d56dbc3362b4.jpg', is_active: true },
  { id: 41, name: 'Бильярд', description: 'Профессиональные бильярдные столы. Русский бильярд и пул.', category_id: 12, ticket_image_url: 'https://www.billiard1.ru/upload/iblock/ac3/zgvvg7n3j88pmgo8vvr7checl7qxtw64.jpg', is_active: true },
  { id: 42, name: 'Боулинг', description: 'Современные дорожки для боулинга. Идеально для семейного отдыха и корпоративов.', category_id: 13, ticket_image_url: 'https://www.kidsreview.ru/sites/default/files/sections/79.jpg?1', is_active: true },
];

export const EVENT_TEMPLATE_IMAGES: Record<number, string> = {
  1: 'https://artchive.ru/res/media/img/oy800/exposition/c22/678496@2x.jpg',
  2: 'https://www.marinabaysands.com/content/dam/revamp/ASMrevamp/VRgallery/VR-Gallery-Photo-Shoot-1-800x490.jpg',
  3: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbou2jpU3dM2uViVkFfBxFw_vmZsD54TMMdQ&s',
  4: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRCG3ocLudpB89cv9srmMsuizRDpASa5HJvw&s',
  5: 'https://s3.afisha.ru/mediastorage/22/5e/a84badf567224497bf0dac225e22.jpg',
  6: 'https://kuda-kazan.ru/uploads/5acced441044b6f1ca31fe364a3003dd.jpg',
  7: 'https://vinchi-interactive.ru/wp-content/uploads/2023/08/vr-111-min.jpg',
  8: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Weapon_history_museum_39.jpg/1200px-Weapon_history_museum_39.jpg',
  9: 'https://it.latuaitalia.ru/wp-content/uploads/2016/04/comune.vicenza.it_2.jpg',
  10: 'https://supernova.eso.org/static/archives/images/screen/upr_IMG_6320-cc.jpg',
  11: 'https://www.kvestinfo.ru/upload/iblock/30b/30b170bfe799ac5a951a534d0a58cce3_500x335.jpg',
  12: 'https://nsk.mir-kvestov.ru/uploads/quest_photos/34566/kvest-obitel-proklyatyh-quest-stars-323337fe_large.jpg?v=1761571873',
  13: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvdDgoVd6R71aL-58y3jST7r2uYtBwxVwflA&s',
  14: 'https://qimnata.com/dist/pict_rooms/NAX8ueFt.jpg',
  15: 'https://staryj-oskol.mir-kvestov.ru/uploads/quest_photos/7652/kvest-mashina-vremeni-kvest-mashina-8b206cd5_large.jpg?v=1762855471',
  16: 'https://questhunter.info/wp-content/uploads/sites/9/2023/10/79.jpg',
  17: 'https://mir-kvestov.ru/uploads/quest_photos/26054/kvest-outlast-quest-stars-3e78602f.jpg?v=1761644183',
  18: 'https://topkvest.by/storage/thumb/quest_image/w800_h600_01K33PHCKAXSDG2C727MJBY1NW.jpeg',
  19: 'https://ulet.pro/sites/default/files/field/image/blog_post/aerotruba-bezopasnyy-sposob.jpg',
  20: 'https://resize.tripster.ru/CwGIW9nfE-TxrqgFc9pbT_yWhas=/fit-in/1220x600/filters:no_upscale()/https://cdn.tripster.ru/photos/d77e8130-139a-4c81-9faa-444d14603983.jpg',
  21: 'https://avatars.mds.yandex.net/get-altay/14112077/2a00000191e1042ff59bc038768f19a644a3/L_height',
  22: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_VzElIKBhcpDFrp1foiRI475b-PZrLRqXAg&s',
  23: 'https://cdn-ua.bodo.gift/resize/upload/files/cm-experience/103/102695/images_file/all_all_big-t1585036987-r1w768h425q90zc1.jpg',
  24: 'https://cdn-ua.bodo.gift/resize/upload/files/cm-experience/106/105781/images_file/all_all_big-t1701090100-r1w568h318q90zc1.jpg',
  25: 'https://s0.rbk.ru/v6_top_pics/media/img/2/37/347243227110372.webp',
  26: 'https://2l-pub.ru/upload/medialibrary/72a/vt51vdajv2yqu8ewl936b3e32i8ou3ph.jpeg',
  27: 'https://welcome.mosreg.ru/storage/images/event/2023/04/img_642e9feb3b4ba.jpg',
  28: 'https://lh6.googleusercontent.com/proxy/buGsdzad1b1jwTVf-lwwU1UR7E0_PJ1eROwVYcmt0lS9TZV1JXC2QXp-ztZvkzTl2BM9vdBObWiov4CPAf7zivUYyvGCrT1l',
  29: 'https://avatars.mds.yandex.net/get-altay/11302718/2a000001901a6a33284430327503fe56714b/L_height',
  30: 'https://www.limuzynki.pl/wpcu/2023/06/wnetrze-party-bus-3.jpg',
  32: 'https://www.ru.emb-japan.go.jp/japan2018/common/images/article/mo7193-3.jpg',
  33: 'https://tomsk.ultrapodarki.ru/upload/iblock/fce/fce734cf7f9f5588ba297d6595a87028.jpg',
  34: 'https://www.afisha.uz/uploads/media/2024/04/d401374706701708c82b728d4964dcfa_l.jpg',
  36: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTPDX4LzFElEKGMHX567kVuLeeUEnt74ocsw&s',
  37: 'https://i.ytimg.com/vi/G3WxM4mhEFA/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGBogLSh_MA8=&rs=AOn4CLBdS0Mhc_0gOtzesYrVnWSO7BF9Vg',
  38: 'https://i.pinimg.com/736x/62/ca/60/62ca60ed68725859f3a27d4c7193a71e.jpg',
  39: 'https://img.restoclub.ru/uploads/article/9/8/d/7/98d703b781f23fc2db166497664d8b42_w828_h552--big.jpg',
  40: 'https://images.aif.by/007/836/a70cc50074418a1821b4d56dbc3362b4.jpg',
  41: 'https://www.billiard1.ru/upload/iblock/ac3/zgvvg7n3j88pmgo8vvr7checl7qxtw64.jpg',
  42: 'https://www.kidsreview.ru/sites/default/files/sections/79.jpg?1',
};
